/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateapp;

import java.util.ArrayList;

/**
 *
 * @author shaun
 */
public class seaGUI extends javax.swing.JFrame {
    private ArrayList<sea> sea;

    /**
     * Creates new form seaGUI
     */
    public seaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgJpnl = new javax.swing.JPanel();
        leftJpnl = new javax.swing.JPanel();
        welcomeJlbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rightJpnl = new javax.swing.JPanel();
        loginJlbl = new javax.swing.JLabel();
        emailJlbl = new javax.swing.JLabel();
        passwordJlbl = new javax.swing.JLabel();
        ageJlbl = new javax.swing.JLabel();
        emailJtf = new javax.swing.JTextField();
        passwordJtf = new javax.swing.JTextField();
        ageJtf = new javax.swing.JTextField();
        loginJbtn = new javax.swing.JButton();
        accountJlbl = new javax.swing.JLabel();
        createJbtn = new javax.swing.JButton();
        homeJtbn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        bgJpnl.setBackground(new java.awt.Color(255, 255, 255));

        leftJpnl.setBackground(new java.awt.Color(0, 153, 153));

        welcomeJlbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeJlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcomeJlbl.setText("WELCOME");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("TO THE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("SEA LIFE");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("APPLICATION");

        javax.swing.GroupLayout leftJpnlLayout = new javax.swing.GroupLayout(leftJpnl);
        leftJpnl.setLayout(leftJpnlLayout);
        leftJpnlLayout.setHorizontalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(welcomeJlbl))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        leftJpnlLayout.setVerticalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(welcomeJlbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        rightJpnl.setBackground(new java.awt.Color(255, 255, 255));

        loginJlbl.setBackground(new java.awt.Color(0, 0, 0));
        loginJlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginJlbl.setForeground(new java.awt.Color(0, 153, 153));
        loginJlbl.setText("LOGIN");

        emailJlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailJlbl.setText("Email:");

        passwordJlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordJlbl.setText("Password");

        ageJlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageJlbl.setText("Age:");

        emailJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJtfActionPerformed(evt);
            }
        });

        loginJbtn.setBackground(new java.awt.Color(255, 255, 102));
        loginJbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginJbtn.setText("Login");
        loginJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJbtnActionPerformed(evt);
            }
        });

        accountJlbl.setText("I don't have an account");

        createJbtn.setBackground(new java.awt.Color(255, 255, 102));
        createJbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createJbtn.setText("Create Account");
        createJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJbtnActionPerformed(evt);
            }
        });

        homeJtbn.setBackground(new java.awt.Color(255, 255, 102));
        homeJtbn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homeJtbn.setText("Menu");
        homeJtbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJtbnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightJpnlLayout = new javax.swing.GroupLayout(rightJpnl);
        rightJpnl.setLayout(rightJpnlLayout);
        rightJpnlLayout.setHorizontalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordJlbl)
                            .addComponent(ageJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rightJpnlLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(loginJbtn))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addComponent(homeJtbn)
                        .addGap(153, 153, 153)
                        .addComponent(loginJlbl))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(accountJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(createJbtn)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        rightJpnlLayout.setVerticalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginJlbl)
                    .addComponent(homeJtbn))
                .addGap(18, 18, 18)
                .addComponent(emailJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordJlbl)
                .addGap(2, 2, 2)
                .addComponent(passwordJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ageJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ageJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(loginJbtn)
                .addGap(44, 44, 44)
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountJlbl)
                    .addComponent(createJbtn))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgJpnlLayout = new javax.swing.GroupLayout(bgJpnl);
        bgJpnl.setLayout(bgJpnlLayout);
        bgJpnlLayout.setHorizontalGroup(
            bgJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgJpnlLayout.createSequentialGroup()
                .addComponent(leftJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgJpnlLayout.setVerticalGroup(
            bgJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgJpnlLayout.createSequentialGroup()
                .addComponent(rightJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJtfActionPerformed

    private void createJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJbtnActionPerformed
        // TODO add your handling code here:
        signupGUI myGUI = new signupGUI(); 
        myGUI.setVisible(true);
        this.dispose();   //for the gui to get rid of the old pop ups 
    }//GEN-LAST:event_createJbtnActionPerformed

    private void loginJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJbtnActionPerformed
        // TODO add your handling code here:
        shaunaaskGUI myGUI = new shaunaaskGUI(); 
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginJbtnActionPerformed

    private void homeJtbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJtbnActionPerformed
        // TODO add your handling code here:
        welcomeGUI myGUI = new welcomeGUI(); //opening up the seaGUI
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeJtbnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountJlbl;
    private javax.swing.JLabel ageJlbl;
    private javax.swing.JTextField ageJtf;
    private javax.swing.JPanel bgJpnl;
    private javax.swing.JButton createJbtn;
    private javax.swing.JLabel emailJlbl;
    private javax.swing.JTextField emailJtf;
    private javax.swing.JButton homeJtbn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel leftJpnl;
    private javax.swing.JButton loginJbtn;
    private javax.swing.JLabel loginJlbl;
    private javax.swing.JLabel passwordJlbl;
    private javax.swing.JTextField passwordJtf;
    private javax.swing.JPanel rightJpnl;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
