/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateapp;

import javax.swing.JOptionPane;

/**
 *
 * @author shauna kirwan kelly
 */
public class wasteGUI extends javax.swing.JFrame {

    /**
     * Creates new form wasteGUI
     */
    public wasteGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftJpnl = new javax.swing.JPanel();
        welcomeJlbl = new javax.swing.JLabel();
        welcome2Jlbl = new javax.swing.JLabel();
        welcome3Jlbl = new javax.swing.JLabel();
        rightJpnl = new javax.swing.JPanel();
        titleJlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ask1Jtf = new javax.swing.JLabel();
        daysJtf = new javax.swing.JTextField();
        ask2Jlbl = new javax.swing.JLabel();
        timesJtf = new javax.swing.JTextField();
        submitJbtn = new javax.swing.JButton();
        backJbtn = new javax.swing.JButton();
        wasteJtf = new javax.swing.JTextField();
        tipsJbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJpnl.setBackground(new java.awt.Color(0, 153, 153));

        welcomeJlbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeJlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcomeJlbl.setText("WELCOME");

        welcome2Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome2Jlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcome2Jlbl.setText("THIS IS THE");

        welcome3Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome3Jlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcome3Jlbl.setText("WASTE CALCULATOR");

        rightJpnl.setBackground(new java.awt.Color(255, 255, 255));

        titleJlbl.setBackground(new java.awt.Color(0, 0, 0));
        titleJlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleJlbl.setForeground(new java.awt.Color(0, 153, 153));
        titleJlbl.setText("PLEASE ENTER YOUR INFORMATION BELOW");

        jLabel1.setText("Please enter the type of waste you use the most");

        ask1Jtf.setText("How many days a week would you throw out this waste?");

        ask2Jlbl.setText("How many times a day would you throw out this waste?");

        submitJbtn.setBackground(new java.awt.Color(255, 255, 102));
        submitJbtn.setText("Submit");
        submitJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJbtnActionPerformed(evt);
            }
        });

        backJbtn.setBackground(new java.awt.Color(255, 255, 102));
        backJbtn.setText("Back");
        backJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbtnActionPerformed(evt);
            }
        });

        tipsJbtn.setBackground(new java.awt.Color(255, 255, 102));
        tipsJbtn.setText("Tips");
        tipsJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipsJbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightJpnlLayout = new javax.swing.GroupLayout(rightJpnl);
        rightJpnl.setLayout(rightJpnlLayout);
        rightJpnlLayout.setHorizontalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightJpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleJlbl)
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timesJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ask2Jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ask1Jtf, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wasteJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJbtn))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipsJbtn)
                            .addComponent(submitJbtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightJpnlLayout.setVerticalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJbtn)
                .addGap(36, 36, 36)
                .addComponent(titleJlbl)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wasteJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ask1Jtf)
                .addGap(18, 18, 18)
                .addComponent(daysJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ask2Jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(timesJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitJbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(tipsJbtn)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout leftJpnlLayout = new javax.swing.GroupLayout(leftJpnl);
        leftJpnl.setLayout(leftJpnlLayout);
        leftJpnlLayout.setHorizontalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcome2Jlbl)
                            .addComponent(welcomeJlbl))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftJpnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(welcome3Jlbl)
                        .addGap(27, 27, 27)))
                .addComponent(rightJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        leftJpnlLayout.setVerticalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(welcomeJlbl)
                .addGap(12, 12, 12)
                .addComponent(welcome2Jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcome3Jlbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(rightJpnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftJpnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJbtnActionPerformed
        // TODO add your handling code here:
        // Get the type of waste the user has inputted
        String waste = wasteJtf.getText();
        String days = daysJtf.getText();
        String times = timesJtf.getText();

        // Checking if waste, days, or times is empty and providing error messages
        if (waste.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid type of waste e.g Plastic, Compost, Paper or Electronic");
        }

        if (days.isEmpty() || times.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number so your waste can be calculated");
        }

        // convert the string to integer because in java class i have days and times saved as integers
        //i had to put it below the isEmpty because it wouldnt work being above it
        int daysAWeek = Integer.parseInt(days);
        int timesADay = Integer.parseInt(times);

        // assigning weight values to the different types of waste
        double wasteKg = 0;

        if (waste.equalsIgnoreCase("Plastic")) {
            wasteKg = 0.5;  // 0.5kg of waste for plastic
        } else if (waste.equalsIgnoreCase("Compost")) {
            wasteKg = 0.1;
        } else if (waste.equalsIgnoreCase("Paper")) {
            wasteKg = 0.3;
        } else if (waste.equalsIgnoreCase("Electronic")) {
            wasteKg = 0.8;
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a valid type of waste such as Plastic, Compost, Paper, or Electronic");
        }

        /*for the weekly waste im multiplying how many days a
        week and how many times a day the user throws out waste multiplied by the weight of the waste*/
        double weeklyWaste = daysAWeek * timesADay * wasteKg;
        double monthlyWaste = weeklyWaste * 4;  // im multiplying the weeklywaste by 4

        //displaying how much waste the user creates
        JOptionPane.showMessageDialog(null, "You create " + weeklyWaste + " kg of " + waste + " waste a week");
        JOptionPane.showMessageDialog(null, "You create " + monthlyWaste + " kg of " + waste + " waste a month");

        // Show tips button
        JOptionPane.showMessageDialog(null, "Press the tips button below to get tips on how to help the environment");
        tipsJbtn.setVisible(true);

    }//GEN-LAST:event_submitJbtnActionPerformed

    private void backJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbtnActionPerformed
        // TODO add your handling code here:
        shaunaaskGUI myGUI = new shaunaaskGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJbtnActionPerformed

    private void tipsJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipsJbtnActionPerformed
        // TODO add your handling code here:
        impactGUI myGUI = new impactGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tipsJbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wasteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wasteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wasteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wasteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wasteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ask1Jtf;
    private javax.swing.JLabel ask2Jlbl;
    private javax.swing.JButton backJbtn;
    private javax.swing.JTextField daysJtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel leftJpnl;
    private javax.swing.JPanel rightJpnl;
    private javax.swing.JButton submitJbtn;
    private javax.swing.JTextField timesJtf;
    private javax.swing.JButton tipsJbtn;
    private javax.swing.JLabel titleJlbl;
    private javax.swing.JTextField wasteJtf;
    private javax.swing.JLabel welcome2Jlbl;
    private javax.swing.JLabel welcome3Jlbl;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
