/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateapp;

/**
 *
 * @author shauna kirwan kelly
 */
public class welcomeGUI extends javax.swing.JFrame {

    /**
     * Creates new form welcomeGUI
     */
    public welcomeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftJpnl = new javax.swing.JPanel();
        welcomeJlbl = new javax.swing.JLabel();
        welcome2Jlbl = new javax.swing.JLabel();
        welcome3Jlbl = new javax.swing.JLabel();
        welcome4Jlbl = new javax.swing.JLabel();
        rightJpnl = new javax.swing.JPanel();
        climateactionJlbl = new javax.swing.JLabel();
        shaunaJbtn = new javax.swing.JButton();
        titleJlbl = new javax.swing.JLabel();
        sealifeJlbl1 = new javax.swing.JLabel();
        linJbtn = new javax.swing.JButton();
        landlifeJlbl = new javax.swing.JLabel();
        shemenJbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJpnl.setBackground(new java.awt.Color(0, 255, 153));

        welcomeJlbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeJlbl.setForeground(new java.awt.Color(0, 0, 0));
        welcomeJlbl.setText("WELCOME");

        welcome2Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome2Jlbl.setForeground(new java.awt.Color(0, 0, 0));
        welcome2Jlbl.setText("TO THE");

        welcome3Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome3Jlbl.setForeground(new java.awt.Color(0, 0, 0));
        welcome3Jlbl.setText("CLIMATE ACTION");

        welcome4Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome4Jlbl.setForeground(new java.awt.Color(0, 0, 0));
        welcome4Jlbl.setText("APPLICATION");

        rightJpnl.setBackground(new java.awt.Color(255, 255, 255));

        climateactionJlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        climateactionJlbl.setText("Lin's information about climate action!");

        shaunaJbtn.setBackground(new java.awt.Color(0, 153, 153));
        shaunaJbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        shaunaJbtn.setText("Sea Life");
        shaunaJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shaunaJbtnActionPerformed(evt);
            }
        });

        titleJlbl.setBackground(new java.awt.Color(0, 0, 0));
        titleJlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleJlbl.setForeground(new java.awt.Color(0, 0, 0));
        titleJlbl.setText("PLEASE SELECT WHAT YOU WOULD LIKE TO LEARN ABOUT");

        sealifeJlbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sealifeJlbl1.setText("Shauna's Information about sea life!");

        linJbtn.setBackground(new java.awt.Color(255, 102, 102));
        linJbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        linJbtn.setText("Climate Action");
        linJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linJbtnActionPerformed(evt);
            }
        });

        landlifeJlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        landlifeJlbl.setText("Shemen's information about land life!");

        shemenJbtn.setBackground(new java.awt.Color(102, 255, 102));
        shemenJbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        shemenJbtn.setText("Land Life");
        shemenJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shemenJbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightJpnlLayout = new javax.swing.GroupLayout(rightJpnl);
        rightJpnl.setLayout(rightJpnlLayout);
        rightJpnlLayout.setHorizontalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(titleJlbl))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(climateactionJlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sealifeJlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(landlifeJlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(linJbtn))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(shaunaJbtn))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(shemenJbtn)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        rightJpnlLayout.setVerticalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleJlbl)
                .addGap(42, 42, 42)
                .addComponent(climateactionJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(linJbtn)
                .addGap(28, 28, 28)
                .addComponent(sealifeJlbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shaunaJbtn)
                .addGap(18, 18, 18)
                .addComponent(landlifeJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shemenJbtn)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftJpnlLayout = new javax.swing.GroupLayout(leftJpnl);
        leftJpnl.setLayout(leftJpnlLayout);
        leftJpnlLayout.setHorizontalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(welcomeJlbl))
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(welcome2Jlbl))
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(welcome3Jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(welcome4Jlbl)))
                .addGap(41, 41, 41)
                .addComponent(rightJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        leftJpnlLayout.setVerticalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(welcomeJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcome2Jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcome3Jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcome4Jlbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(rightJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shaunaJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shaunaJbtnActionPerformed
        // TODO add your handling code here:
        seaGUI myGUI = new seaGUI();
        myGUI.setVisible(true);
        this.dispose(); //gets rid of old GUIs to prevent multiple windows at once
    }//GEN-LAST:event_shaunaJbtnActionPerformed

    private void linJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linJbtnActionPerformed
        // TODO add your handling code here:
        ClimateGUI myGUI = new ClimateGUI();
        myGUI.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_linJbtnActionPerformed

    private void shemenJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shemenJbtnActionPerformed
        // TODO add your handling code here:
        Menu2GUI myGUI = new Menu2GUI();
        myGUI.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_shemenJbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel climateactionJlbl;
    private javax.swing.JLabel landlifeJlbl;
    private javax.swing.JPanel leftJpnl;
    private javax.swing.JButton linJbtn;
    private javax.swing.JPanel rightJpnl;
    private javax.swing.JLabel sealifeJlbl1;
    private javax.swing.JButton shaunaJbtn;
    private javax.swing.JButton shemenJbtn;
    private javax.swing.JLabel titleJlbl;
    private javax.swing.JLabel welcome2Jlbl;
    private javax.swing.JLabel welcome3Jlbl;
    private javax.swing.JLabel welcome4Jlbl;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
