/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateapp;

import javax.swing.JOptionPane;

/**
 *
 * @author shauna kirwan kelly
 */
public class donateGUI extends javax.swing.JFrame {

    /**
     * Creates new form donateGUI
     */
    public donateGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftJpnl = new javax.swing.JPanel();
        welcomeJlbl = new javax.swing.JLabel();
        welcome2Jlbl = new javax.swing.JLabel();
        welcome3Jlbl = new javax.swing.JLabel();
        rightJpnl = new javax.swing.JPanel();
        titleJlbl = new javax.swing.JLabel();
        askJlbl = new javax.swing.JLabel();
        submitJbtn = new javax.swing.JButton();
        backJbtn = new javax.swing.JButton();
        donateJtf = new javax.swing.JTextField();
        monthJlbl = new javax.swing.JLabel();
        monthlyJlbl = new javax.swing.JLabel();
        monthlyJtf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJpnl.setBackground(new java.awt.Color(0, 153, 153));

        welcomeJlbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeJlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcomeJlbl.setText("WELCOME");

        welcome2Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome2Jlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcome2Jlbl.setText("THIS IS THE");

        welcome3Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome3Jlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcome3Jlbl.setText("DONATION CENTRE");

        javax.swing.GroupLayout leftJpnlLayout = new javax.swing.GroupLayout(leftJpnl);
        leftJpnl.setLayout(leftJpnlLayout);
        leftJpnlLayout.setHorizontalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeJlbl)
                            .addComponent(welcome2Jlbl)))
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(welcome3Jlbl)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        leftJpnlLayout.setVerticalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(welcomeJlbl)
                .addGap(18, 18, 18)
                .addComponent(welcome2Jlbl)
                .addGap(18, 18, 18)
                .addComponent(welcome3Jlbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightJpnl.setBackground(new java.awt.Color(255, 255, 255));

        titleJlbl.setBackground(new java.awt.Color(0, 0, 0));
        titleJlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleJlbl.setForeground(new java.awt.Color(0, 153, 153));
        titleJlbl.setText("PLEASE ENTER YOUR INFORMATION BELOW");

        askJlbl.setText("Please enter how much you would like to donate");

        submitJbtn.setBackground(new java.awt.Color(255, 255, 102));
        submitJbtn.setText("Submit");
        submitJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJbtnActionPerformed(evt);
            }
        });

        backJbtn.setBackground(new java.awt.Color(255, 255, 102));
        backJbtn.setText("Back");
        backJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbtnActionPerformed(evt);
            }
        });

        monthJlbl.setText("If you would like to make a monthly donation , enter below");

        monthlyJlbl.setText("How much would you like to donate to us a month");

        javax.swing.GroupLayout rightJpnlLayout = new javax.swing.GroupLayout(rightJpnl);
        rightJpnl.setLayout(rightJpnlLayout);
        rightJpnlLayout.setHorizontalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJbtn))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(submitJbtn))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(askJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleJlbl)
                            .addComponent(monthlyJlbl)
                            .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(monthlyJtf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(donateJtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                            .addComponent(monthJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightJpnlLayout.setVerticalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJbtn)
                .addGap(36, 36, 36)
                .addComponent(titleJlbl)
                .addGap(18, 18, 18)
                .addComponent(askJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(donateJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthJlbl)
                .addGap(18, 18, 18)
                .addComponent(monthlyJlbl)
                .addGap(18, 18, 18)
                .addComponent(monthlyJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(submitJbtn)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJbtnActionPerformed
        // TODO add your handling code here:
        int monthly = Integer.parseInt(monthlyJtf.getText());
        int donation = Integer.parseInt(donateJtf.getText());
        //checking if the donation amount is less than 0
        if (donation < 0) {
            JOptionPane.showMessageDialog(null, "Please enter a valid amount to donate");
        }
        else {
            JOptionPane.showMessageDialog(null,"You have decided to donate "+donation+ "euro to us. Thank you.");
            JOptionPane.showMessageDialog(null,"You have chosen to donate "+monthly+ "euro to us a month. Thank you");
            JOptionPane.showMessageDialog(null,"You have reached the end of our application. I will now take you back to the menu");

            welcomeGUI myGUI = new welcomeGUI();  //bringing the user back to the beginning
            myGUI.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_submitJbtnActionPerformed

    private void backJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbtnActionPerformed
        // TODO add your handling code here:
        shaunaaskGUI myGUI = new shaunaaskGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(donateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(donateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(donateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(donateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donateGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel askJlbl;
    private javax.swing.JButton backJbtn;
    private javax.swing.JTextField donateJtf;
    private javax.swing.JPanel leftJpnl;
    private javax.swing.JLabel monthJlbl;
    private javax.swing.JLabel monthlyJlbl;
    private javax.swing.JTextField monthlyJtf;
    private javax.swing.JPanel rightJpnl;
    private javax.swing.JButton submitJbtn;
    private javax.swing.JLabel titleJlbl;
    private javax.swing.JLabel welcome2Jlbl;
    private javax.swing.JLabel welcome3Jlbl;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
