/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateapp;

import javax.swing.JOptionPane;

/**
 *
 * @author shauna kirwan kelly
 */
public class impactGUI extends javax.swing.JFrame {
        String[] tips ={
        "Reduce Plastic Use: Avoid single-use plastics like straws, bottles. \n"
            + "Try use re-usable straws and bottles",
        "Clean the beach: pick up your rubbish after yourself when leaving the beach",
        "Support Ocean-Friendly Companies: Choose products from companies that are sustainable \n"
            + "and focus on ocean safe ingredients",
        "Avoid chemicals: Avoid using harmful chemicals in your home or garden, such as leaning products, \n"
            + "they can run off into rivers and oceans.",
        "Eat Sustainable Seafood: Choose seafood that’s caught sustainably, \n"
            + "supporting fishing practices that don’t harm marine life",
        "Educate others: Share with others or on your social media simple tips like these to help the ocean",
        "Water Usage: Don't leave taps running"
    };
    int Tipsindex = 0; 

    /**
     * Creates new form impactGUI
     */
    public impactGUI() {
        initComponents();
        nextJbtn.addActionListener(evt -> nextJbtnActionPerformed(evt)); // i got this from shemens code
        displayTip(); // Display the first tip
    }
        private void displayTip() {
        tipsJlbl.setText(tips[Tipsindex]);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftJpnl = new javax.swing.JPanel();
        welcomeJlbl = new javax.swing.JLabel();
        welcome2Jlbl = new javax.swing.JLabel();
        welcome3Jlbl = new javax.swing.JLabel();
        rightJpnl = new javax.swing.JPanel();
        titleJlbl = new javax.swing.JLabel();
        backJbtn = new javax.swing.JButton();
        nextJbtn = new javax.swing.JButton();
        tipsJlbl = new javax.swing.JLabel();
        donateJlbl = new javax.swing.JLabel();
        yesJbtn = new javax.swing.JButton();
        noJbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJpnl.setBackground(new java.awt.Color(0, 153, 153));

        welcomeJlbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeJlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcomeJlbl.setText("WELCOME");

        welcome2Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome2Jlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcome2Jlbl.setText("THIS IS THE");

        welcome3Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome3Jlbl.setForeground(new java.awt.Color(255, 255, 102));
        welcome3Jlbl.setText("IMPACT APPLICATION");

        rightJpnl.setBackground(new java.awt.Color(255, 255, 255));

        titleJlbl.setBackground(new java.awt.Color(0, 0, 0));
        titleJlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleJlbl.setForeground(new java.awt.Color(0, 153, 153));
        titleJlbl.setText("TIPS ON HOW TO HELP THE ENVIORNMENT");

        backJbtn.setBackground(new java.awt.Color(255, 255, 102));
        backJbtn.setText("Back");
        backJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbtnActionPerformed(evt);
            }
        });

        nextJbtn.setBackground(new java.awt.Color(255, 255, 102));
        nextJbtn.setText("Next");
        nextJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextJbtnActionPerformed(evt);
            }
        });

        donateJlbl.setText("Would you like to donate to saving the oceans?");

        yesJbtn.setBackground(new java.awt.Color(255, 255, 102));
        yesJbtn.setText("Yes");
        yesJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesJbtnActionPerformed(evt);
            }
        });

        noJbtn.setBackground(new java.awt.Color(255, 255, 102));
        noJbtn.setText("No");
        noJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noJbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightJpnlLayout = new javax.swing.GroupLayout(rightJpnl);
        rightJpnl.setLayout(rightJpnlLayout);
        rightJpnlLayout.setHorizontalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addComponent(backJbtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightJpnlLayout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addComponent(titleJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightJpnlLayout.createSequentialGroup()
                        .addComponent(tipsJlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightJpnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextJbtn)
                .addGap(229, 229, 229))
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addComponent(yesJbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noJbtn))
                    .addComponent(donateJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightJpnlLayout.setVerticalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(backJbtn)
                .addGap(28, 28, 28)
                .addComponent(titleJlbl)
                .addGap(105, 105, 105)
                .addComponent(tipsJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(nextJbtn)
                .addGap(30, 30, 30)
                .addComponent(donateJlbl)
                .addGap(18, 18, 18)
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesJbtn)
                    .addComponent(noJbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftJpnlLayout = new javax.swing.GroupLayout(leftJpnl);
        leftJpnl.setLayout(leftJpnlLayout);
        leftJpnlLayout.setHorizontalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeJlbl)
                            .addGroup(leftJpnlLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(welcome2Jlbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addContainerGap(80, Short.MAX_VALUE)
                        .addComponent(welcome3Jlbl)
                        .addGap(35, 35, 35)))
                .addComponent(rightJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        leftJpnlLayout.setVerticalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(welcomeJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcome2Jlbl)
                .addGap(18, 18, 18)
                .addComponent(welcome3Jlbl)
                .addContainerGap(127, Short.MAX_VALUE))
            .addComponent(rightJpnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbtnActionPerformed
        // TODO add your handling code here:
        shaunaaskGUI myGUI = new shaunaaskGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backJbtnActionPerformed

    private void nextJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextJbtnActionPerformed
        // TODO add your handling code here:
        Tipsindex++; //moves onto the next tip in the array
        if (Tipsindex < tips.length) { //checking if there are still more tips to be shown
            displayTip();
        } else {
            JOptionPane.showMessageDialog(null, "There are no more tips available");
        }

    }//GEN-LAST:event_nextJbtnActionPerformed

    private void yesJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesJbtnActionPerformed
        // TODO add your handling code here:
        donateGUI myGUI = new donateGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_yesJbtnActionPerformed

    private void noJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noJbtnActionPerformed
        // TODO add your handling code here:
        welcomeGUI myGUI = new welcomeGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_noJbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(impactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(impactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(impactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(impactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new impactGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJbtn;
    private javax.swing.JLabel donateJlbl;
    private javax.swing.JPanel leftJpnl;
    private javax.swing.JButton nextJbtn;
    private javax.swing.JButton noJbtn;
    private javax.swing.JPanel rightJpnl;
    private javax.swing.JLabel tipsJlbl;
    private javax.swing.JLabel titleJlbl;
    private javax.swing.JLabel welcome2Jlbl;
    private javax.swing.JLabel welcome3Jlbl;
    private javax.swing.JLabel welcomeJlbl;
    private javax.swing.JButton yesJbtn;
    // End of variables declaration//GEN-END:variables
}
