/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package climateapp;

/**
 *
 * @author shauna kirwan kelly
 */
public class welcomeGUI extends javax.swing.JFrame {

    /**
     * Creates new form welcomeGUI
     */
    public welcomeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftJpnl = new javax.swing.JPanel();
        welcomeJlbl = new javax.swing.JLabel();
        welcome2Jlbl = new javax.swing.JLabel();
        welcome3Jlbl = new javax.swing.JLabel();
        welcome4Jlbl = new javax.swing.JLabel();
        rightJpnl = new javax.swing.JPanel();
        titleJlbl = new javax.swing.JLabel();
        sealifeJlbl = new javax.swing.JLabel();
        shaunaJbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJpnl.setBackground(new java.awt.Color(255, 204, 102));

        welcomeJlbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeJlbl.setForeground(new java.awt.Color(0, 0, 0));
        welcomeJlbl.setText("WELCOME");

        welcome2Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome2Jlbl.setForeground(new java.awt.Color(0, 0, 0));
        welcome2Jlbl.setText("TO THE");

        welcome3Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome3Jlbl.setForeground(new java.awt.Color(0, 0, 0));
        welcome3Jlbl.setText("CLIMATE ACTION");

        welcome4Jlbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome4Jlbl.setForeground(new java.awt.Color(0, 0, 0));
        welcome4Jlbl.setText("APPLICATION");

        javax.swing.GroupLayout leftJpnlLayout = new javax.swing.GroupLayout(leftJpnl);
        leftJpnl.setLayout(leftJpnlLayout);
        leftJpnlLayout.setHorizontalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(welcome2Jlbl))
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcome4Jlbl)
                            .addComponent(welcomeJlbl)))
                    .addGroup(leftJpnlLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(welcome3Jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        leftJpnlLayout.setVerticalGroup(
            leftJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpnlLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(welcomeJlbl)
                .addGap(18, 18, 18)
                .addComponent(welcome2Jlbl)
                .addGap(18, 18, 18)
                .addComponent(welcome3Jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcome4Jlbl)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        rightJpnl.setBackground(new java.awt.Color(255, 255, 255));

        titleJlbl.setBackground(new java.awt.Color(0, 0, 0));
        titleJlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleJlbl.setForeground(new java.awt.Color(0, 0, 0));
        titleJlbl.setText("PLEASE SELECT WHAT YOU WOULD LIKE TO LEARN ABOUT");

        sealifeJlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sealifeJlbl.setText("Shauna's Information about sea life!");

        shaunaJbtn.setBackground(new java.awt.Color(0, 153, 153));
        shaunaJbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        shaunaJbtn.setText("Sea Life");
        shaunaJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shaunaJbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightJpnlLayout = new javax.swing.GroupLayout(rightJpnl);
        rightJpnl.setLayout(rightJpnlLayout);
        rightJpnlLayout.setHorizontalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightJpnlLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(sealifeJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGroup(rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(titleJlbl))
                    .addGroup(rightJpnlLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(shaunaJbtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rightJpnlLayout.setVerticalGroup(
            rightJpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightJpnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleJlbl)
                .addGap(111, 111, 111)
                .addComponent(sealifeJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shaunaJbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rightJpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightJpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shaunaJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shaunaJbtnActionPerformed
        // TODO add your handling code here:
        seaGUI myGUI = new seaGUI();
        myGUI.setVisible(true);
        this.dispose(); //gets rid of old GUIs to prevent multiple windows at once
    }//GEN-LAST:event_shaunaJbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel leftJpnl;
    private javax.swing.JPanel rightJpnl;
    private javax.swing.JLabel sealifeJlbl;
    private javax.swing.JButton shaunaJbtn;
    private javax.swing.JLabel titleJlbl;
    private javax.swing.JLabel welcome2Jlbl;
    private javax.swing.JLabel welcome3Jlbl;
    private javax.swing.JLabel welcome4Jlbl;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
